### ISSUE TITLE
Cannot share images from within Diaspora to Telegram

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#42]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1 CopperheadOS
- **Pod:** doesn't matter
- **App source:** F-Droid
- **App version:** HEAD

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/Diaspora-for-Android/diaspora-android/blob/master/CONTRIBUTING.md
#### Steps to reproduce
1. Long press on image and select "Share image"
2. select Telegram contact
#### Expected result

What is the expected output? 
Image appears in selected Telegram chat

What do you see instead?
Nothing happens
#### Debug output

```
08-02 21:32:11.421 12800-12800/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.telegram.messenger, PID: 12800
                                                   java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                       at java.util.regex.Matcher.reset(Matcher.java:177)
                                                       at java.util.regex.Matcher.<init>(Matcher.java:90)
                                                       at java.util.regex.Pattern.matcher(Pattern.java:297)
                                                       at org.telegram.ui.LaunchActivity.handleIntent(LaunchActivity.java:646)
                                                       at org.telegram.ui.LaunchActivity.onNewIntent(LaunchActivity.java:1366)
                                                       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1212)
                                                       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1224)
                                                       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2545)
                                                       at android.app.ActivityThread.performNewIntents(ActivityThread.java:2557)
                                                       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2566)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1416)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ExecInit.main(ExecInit.java:56)
                                                       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
08-02 21:32:11.422 12800-12800/? E/AndroidRuntime: Error reporting crash
                                                   java.lang.RuntimeException: Bad file descriptor
                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                       at android.os.BinderProxy.transact(Binder.java:503)
                                                       at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4427)
                                                       at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```

This might be a bug on Telegrams side (Telegram-FOSS 3.10.1, FDroid), sharing to Conversations works as intended.

**Comment by vanitasvitae** [comment]
Edit: May be an upstream issue: https://github.com/slp/Telegram-FOSS/issues/109

Edit: Pretty sure, its just an upstream bug.
