### ISSUE TITLE
Proxy feature not working on some devices

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#96]
#### General information
- **Device:** Huawei T1-701u Tablet
- **Android Version:** Android 4.4.2
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD

#### Steps to reproduce
1. Set proxy (I tried with Orbot Proxy preset
2. Open onion pod
#### Expected result

**What is the expected output?** 
Onion site is loaded correctly.
If chosen Pod is a "normal" pod, the site gets loaded over the tor network.

**What do you see instead?**
Onion pods show loading error.
Normal pods load, but I guess the app is simply not using the Orbot proxy

I'll try to find out, whether this has to do with the fact, that newer Android versions are using a WebView based on Chromium. Maybe NetCipher can only configure proxy servers properly on Chromium-based WebViews and fails on older ones. If that is true, we should disable the proxy feature on older Android versions.
#### Debug output

```
10-25 20:04:23.238 20610-20610/com.github.dfa.diaspora_android D/d*-com.github.dfa.diaspora_android.activity.SettingsActivity: ProxySettings changed.
10-25 20:04:23.238 20610-20610/com.github.dfa.diaspora_android D/d*-com.github.dfa.diaspora_android.util.ProxyHandler: UpdateProxySettings()
10-25 20:04:23.248 20610-20610/com.github.dfa.diaspora_android V/OrbotHelpher: mLoadedApk
10-25 20:04:23.248 20610-20610/com.github.dfa.diaspora_android V/OrbotHelpher: java.lang.NoSuchFieldException: mLoadedApk
                                                                                   at java.lang.Class.getField(Class.java:724)
                                                                                   at info.guardianproject.netcipher.webkit.WebkitProxy.setKitKatProxy(WebkitProxy.java:316)
                                                                                   at info.guardianproject.netcipher.webkit.WebkitProxy.setProxy(WebkitProxy.java:76)
                                                                                   at com.github.dfa.diaspora_android.util.ProxyHandler.updateProxySettings(ProxyHandler.java:68)
                                                                                   at com.github.dfa.diaspora_android.activity.SettingsActivity.onStop(SettingsActivity.java:123)
                                                                                   at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1222)
                                                                                   at android.app.Activity.performStop(Activity.java:5474)
                                                                                   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3765)
                                                                                   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3824)
                                                                                   at android.app.ActivityThread.access$1700(ActivityThread.java:143)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5398)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
10-25 20:04:23.248 20610-20610/com.github.dfa.diaspora_android E/ProxySettings: Exception setting WebKit proxy through android.net.ProxyProperties: java.lang.ClassNotFoundException: android.webkit.WebViewCore
```

**Comment by vanitasvitae** [comment]
Edit: That exception happens on most devices I tested so far. I don't really know, why the issue occurs on my test device though, since it doesn't happen on eg. an API 17 emulator...

**Comment by vanitasvitae** [comment]
Since this is very likely an upstream issue, I'll move this to the 0.2.2 milestone, since I can't really do anything about this right now. I'll add a notice to the proxy settings, that it might not work on some devices though.

**Comment by gsantner** [comment]
Reopen if needed. 
Closing.
