### ISSUE TITLE
WebView crashes on Copperhead OS Nougat

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#97]
#### General information
- **Device:** Nexus 6p
- **Android Version:** 7.0.0 CopperheadOS
- **Pod:** pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD

#### Steps to reproduce
1. Open app and let stream load
#### Expected result

**What is the expected output?** 
No crash

**What do you see instead?**
App crashes sometimes after ~4-5 secs. If the crash once happened, it will happen most starts afterwards. This can be fixed by deleting all app data.
#### Debug output

Edit: Whoops, wrong log...

```
10-25 22:35:46.216 16967-16967/? D/AndroidRuntime: Shutting down VM
10-25 22:35:46.217 16967-16967/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.github.dfa.diaspora_android, PID: 16967
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                       at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:1181)
                                                       at org.chromium.android_webview.DefaultVideoPosterRequestHandler$1.run(DefaultVideoPosterRequestHandler.java:39)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6080)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
                                                       at com.android.internal.os.ExecInit.main(ExecInit.java:56)
                                                       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
10-25 22:35:46.219 16967-16967/? E/AndroidRuntime: Error reporting crash
                                                   java.lang.RuntimeException: Bad file descriptor
                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                       at android.os.BinderProxy.transact(Binder.java:615)
                                                       at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5103)
                                                       at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
10-25 22:35:46.219 16967-16967/? I/Process: Sending signal. PID: 16967 SIG: 9
10-25 22:35:46.279 4424-4767/? I/WindowManager: WIN DEATH: Window{2b8301b u0 com.github.dfa.diaspora_android/com.github.dfa.diaspora_android.activity.MainActivity}
```

**Comment by vanitasvitae** [comment]
Edit: Might this be related to Chrome Custom Tabs? (Maybe something goes wrong on warmup)

**Comment by vanitasvitae** [comment]
I'm just playing around on an emulator with API lvl 17 and also here the app often crashes shortly after startup (not always though). Here is a crash log:

```
10-26 20:32:56.955 11553-11553/com.github.dfa.diaspora_android E/Web Console: Uncaught TypeError: Cannot read property 'style' of null at null:1
10-26 20:32:56.955 792-852/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
10-26 20:32:57.175 11553-11553/com.github.dfa.diaspora_android D/TilesManager: Starting TG #0, 0xb87e1110
10-26 20:32:57.175 11553-11622/com.github.dfa.diaspora_android D/TilesManager: Starting TG #0, 0xb858b3b0
10-26 20:32:57.175 11553-11623/com.github.dfa.diaspora_android D/TilesManager: Starting TG #0, 0xb8912040
10-26 20:32:57.175 11553-11624/com.github.dfa.diaspora_android D/TilesManager: Starting TG #0, 0xb88d4560
10-26 20:32:57.175 11553-11625/com.github.dfa.diaspora_android D/TilesManager: Starting TG #0, 0xb88b4580
10-26 20:32:57.175 11553-11626/com.github.dfa.diaspora_android D/TilesManager: Starting TG #0, 0xb88b8e30
10-26 20:32:57.175 11553-11553/com.github.dfa.diaspora_android D/TilesManager: new EGLContext from framework: b86bf500 
10-26 20:32:57.175 11553-11553/com.github.dfa.diaspora_android D/GLWebViewState: Reinit shader
10-26 20:32:57.285 11553-11553/com.github.dfa.diaspora_android D/GLWebViewState: Reinit transferQueue
10-26 20:32:57.305 11553-11553/com.github.dfa.diaspora_android D/TilesManager: new EGLContext from framework: b86bf500 
10-26 20:32:57.305 11553-11553/com.github.dfa.diaspora_android D/GLWebViewState: Reinit shader
10-26 20:32:57.384 11553-11553/com.github.dfa.diaspora_android D/GLWebViewState: Reinit transferQueue

                                                                                 [ 10-26 20:32:57.395 11553:11623 D/         ]
                                                                                 HostConnection::get() New Host Connection established 0xb88b2120, tid 11623
10-26 20:33:03.356 792-792/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
10-26 20:33:03.475 11553-11589/com.github.dfa.diaspora_android A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 11589 (WebViewCoreThre)
10-26 20:33:03.555 11553-11584/com.github.dfa.diaspora_android V/d*-com.github.dfa.diaspora_android.activity.DiasporaStreamFragment.JavaScriptInterface: DiasporaUserProfile needs refresh; Try to parse JSON
10-26 20:33:03.595 790-790/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-26 20:33:03.595 790-790/? I/DEBUG: Build fingerprint: 'generic_x86/sdk_x86/generic_x86:4.2.2/JB_MR1.1/1742939:eng/test-keys'
10-26 20:33:03.595 790-790/? I/DEBUG: Revision: '0'
10-26 20:33:03.595 790-790/? I/DEBUG: pid: 11553, tid: 11589, name: UNKNOWN  >>> com.github.dfa.diaspora_android <<<
10-26 20:33:03.595 790-790/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
10-26 20:33:03.695 790-790/? I/DEBUG:     eax 00000000  ebx 9a8c6ff4  ecx b8ab7d20  edx 00000000
10-26 20:33:03.695 790-790/? I/DEBUG:     esi b8ca8370  edi b7faf740
10-26 20:33:03.695 790-790/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
10-26 20:33:03.695 790-790/? I/DEBUG:     eip 9a6726f1  ebp b8ca837c  esp 99538410  flags 00010246
10-26 20:33:03.695 790-790/? I/DEBUG: backtrace:
10-26 20:33:03.695 790-790/? I/DEBUG:     #00  pc 002096f1  /system/lib/libchromium_net.so (net::HttpCache::Transaction::DoCacheReadData()+337)
10-26 20:33:03.695 790-790/? I/DEBUG: stack:
10-26 20:33:03.695 790-790/? I/DEBUG:          995383d0  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383d4  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383d8  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383dc  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383e0  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383e4  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383e8  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383ec  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383f0  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383f4  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383f8  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          995383fc  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          99538400  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          99538404  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          99538408  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          9953840c  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:     #00  99538410  b8ca837c  [heap]
10-26 20:33:03.695 790-790/? I/DEBUG:          99538414  9a56dfa6  /system/lib/libchromium_net.so (base::internal::ThreadLocalPlatform::GetValueFromSlot(int&)+6)
10-26 20:33:03.695 790-790/? I/DEBUG:          99538418  9a8c6ff4  /system/lib/libchromium_net.so
10-26 20:33:03.695 790-790/? I/DEBUG:          9953841c  4b705b08  
10-26 20:33:03.695 790-790/? I/DEBUG:          99538420  9a8c7f8c  /system/lib/libchromium_net.so
10-26 20:33:03.695 790-790/? I/DEBUG:          99538424  b865e650  [heap]
10-26 20:33:03.695 790-790/? I/DEBUG:          99538428  00000000  
10-26 20:33:03.695 790-790/? I/DEBUG:          9953842c  9a8c6ff4  /system/lib/libchromium_net.so
10-26 20:33:03.695 790-790/? I/DEBUG:          99538430  b8ab3a60  [heap]
10-26 20:33:03.695 790-790/? I/DEBUG:          99538434  99538474  
10-26 20:33:03.695 790-790/? I/DEBUG:          99538438  b8ca3210  [heap]
10-26 20:33:03.695 790-790/? I/DEBUG:          9953843c  9a666d83  /system/lib/libchromium_net.so (_ZN3net9HttpCache19ProcessPendingQueueEPNS0_11ActiveEntryE.part.172+243)
10-26 20:33:03.695 790-790/? I/DEBUG:          99538440  9953cd6c  
10-26 20:33:03.695 790-790/? I/DEBUG:          99538444  99538474  
10-26 20:33:03.695 790-790/? I/DEBUG:          99538448  b8ab3a60  [heap]
10-26 20:33:03.695 790-790/? I/DEBUG:          9953844c  000003df  
10-26 20:33:03.695 790-790/? I/DEBUG:          ........  ........
10-26 20:33:03.725 1193-1214/system_process I/BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
10-26 20:33:03.735 793-793/? D/Zygote: Process 11553 terminated by signal (11)
10-26 20:33:03.735 1193-1224/system_process W/InputDispatcher: channel 'a7560c80 com.github.dfa.diaspora_android/com.github.dfa.diaspora_android.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-26 20:33:03.735 1193-1224/system_process E/InputDispatcher: channel 'a7560c80 com.github.dfa.diaspora_android/com.github.dfa.diaspora_android.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-26 20:33:03.755 1193-1194/system_process D/dalvikvm: GC_CONCURRENT freed 1864K, 28% free 13519K/18672K, paused 10ms+1ms, total 22ms
10-26 20:33:03.755 1193-1214/system_process D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 6ms
10-26 20:33:03.765 1193-1264/system_process I/ActivityManager: Process com.github.dfa.diaspora_android (pid 11553) has died.
```

**Comment by vanitasvitae** [comment]
Since I can't really do anything about this and I don't know, whether the app also crashes on other devices, I'll add this issue to a latter milestone for now.

**Comment by gsantner** [comment]
I tried to reproduce this on 4 (real) device,  but no crashes

**Comment by vanitasvitae** [comment]
I guess that's good news. Maybe this only affects devices running copperheadOS and emulators...

**Comment by vanitasvitae** [comment]
I added the drawable ic_media_video_poster to the drawables folder in order to prevent the crash above. I tested it for some time and had no crashes since then. I'll close this and open it, if the problem turns out to persist.

**Comment by gsantner** [comment]
Can you push that commit to the release_v0.2.0 branch?

**Comment by vanitasvitae** [comment]
By merging master?

**Comment by vanitasvitae** [comment]
Nevermind, that didn't fix the issue :(

**Comment by gsantner** [comment]
No, just a simple commit on the ` release_v0.2.0` branch^^.
Did you rewrite on master somehow?

**Comment by vanitasvitae** [comment]
It might be this upstream issue: https://code.google.com/p/android/issues/detail?id=211850

**Comment by vanitasvitae** [comment]
https://github.com/copperhead/bugtracker/issues/420

**Comment by vanitasvitae** [comment]
I'll add back the unreliable label, since the issue seems to come and go from build to build. What a strange thing is this?!?

**Comment by vanitasvitae** [comment]
Bookmark: https://stackoverflow.com/questions/27994709/android-how-can-i-attach-a-webview-to-an-activity-after-creating-it-with-the-a

**Comment by vanitasvitae** [comment]
Also possibly interesting: WebViewClient.onReceivedError()

**Comment by vanitasvitae** [comment]
Making use of MutableContextWrappers might have again fixed this issue. I got no crashes for ~ 3 days now. I'll close this and reopen later, in case I get another crash _fingers crossed_

**Comment by vanitasvitae** [comment]
-.-

**Comment by gsantner** [comment]
![ragequit](https://cloud.githubusercontent.com/assets/6735650/20062152/e460e77a-a502-11e6-9252-a0b368cb5396.gif)

**Comment by gsantner** [comment]
I don't think we can do anything about that in our app. Maybe it gets resolved in a newer Copperhead OS update. - Closing
