### ISSUE TITLE
App crashes on API 17 on startup (Related to vector graphics)

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#99]
#### General information
- **Device:** AndroidStudio Emulator with API 17
- **Android Version:** Api 17 emulator
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD

#### Steps to reproduce
1. Open app
#### Expected result

**What is the expected output?** 
App starts normal

**What do you see instead?**
App crashes directly

I guess it has to do with the way icon drawables are set on toolbar entries.
@gsantner I'll assign you to this issue, since I don't have a clue about vector drawables :D
#### Debug output

```
10-26 19:55:36.481 1882-1882/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 android.content.res.Resources$NotFoundException: File res/drawable/ic_notifications_white_48px__layer.xml from drawable resource ID #0x7f020069. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
                                                     at android.content.res.Resources.loadDrawable(Resources.java:1958)
                                                     at android.content.res.Resources.getDrawable(Resources.java:660)
                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185)
                                                     at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                     at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:421)
                                                     at android.support.v7.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:128)
                                                     at android.support.v7.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:211)
                                                     at android.support.v7.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:182)
                                                     at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:197)
                                                     at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:479)
                                                     at android.support.v7.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1144)
                                                     at android.support.v7.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91)
                                                     at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:234)
                                                     at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:283)
                                                     at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1035)
                                                     at android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1058)
                                                     at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:460)
                                                     at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
                                                     at android.os.Handler.handleCallback(Handler.java:725)
                                                     at android.os.Handler.dispatchMessage(Handler.java:92)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_notifications_white_48px.xml from drawable resource ID #0x7f020068
                                                     at android.content.res.Resources.loadDrawable(Resources.java:1958)
                                                     at android.content.res.Resources.getDrawable(Resources.java:660)
                                                     at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:156)
                                                     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:885)
                                                     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
                                                     at android.content.res.Resources.loadDrawable(Resources.java:1955)
                                                     at android.content.res.Resources.getDrawable(Resources.java:660) 
                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346) 
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197) 
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185) 
                                                     at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100) 
                                                     at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:421) 
                                                     at android.support.v7.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:128) 
                                                     at android.support.v7.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:211) 
                                                     at android.support.v7.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:182) 
                                                     at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:197) 
                                                     at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:479) 
                                                     at android.support.v7.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1144) 
                                                     at android.support.v7.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91) 
                                                     at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:234) 
                                                     at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:283) 
                                                     at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1035) 
                                                     at android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1058) 
                                                     at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:460) 
                                                     at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61) 
                                                     at android.os.Handler.handleCallback(Handler.java:725) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
                                                     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
                                                     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
                                                     at android.content.res.Resources.loadDrawable(Resources.java:1955)
                                                     at android.content.res.Resources.getDrawable(Resources.java:660) 
                                                     at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:156) 
                                                     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:885) 
                                                     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822) 
                                                     at android.content.res.Resources.loadDrawable(Resources.java:1955) 
                                                     at android.content.res.Resources.getDrawable(Resources.java:660) 
                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346) 
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197) 
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185) 
                                                     at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100) 
                                                     at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:421) 
                                                     at android.support.v7.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:128) 
                                                     at android.support.v7.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:211) 
                                                     at android.support.v7.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:182) 
                                                     at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:197) 
                                                     at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:479) 
                                                     at android.support.v7.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1144) 
                                                     at android.support.v7.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91) 
                                                     at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:234) 
                                                     at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:283) 
                                                     at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1035) 
                                                     at android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1058) 
                                                     at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:460) 
                                                     at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61) 
                                                     at android.os.Handler.handleCallback(Handler.java:725) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by vanitasvitae** [comment]
https://stackoverflow.com/questions/37615470/support-library-vectordrawable-resourcesnotfoundexception

**Comment by gsantner** [comment]
Did this happen before? Which was the last version that was installed on the system?

**Comment by vanitasvitae** [comment]
Unfortunately I don't know. It did not happen in the version that was installed before, but don't ask me, what version that was :D 
I think adding 

```
AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
```

to App.onCreate() fixed the issue though

**Comment by gsantner** [comment]
The line below was added in the fragment branch from yesterday:  
https://github.com/Diaspora-for-Android/diaspora-android/blob/master/app/build.gradle#L15
Which maybe lead to this. If you have this resolved locally, just push it ;).

**Comment by Renish94** [comment]
### **1. Create a class which extends to Application (android.app.Application)**

```
public class MyApplicationClass extends Application
{
    @Override
    public void onCreate()
    {
        super.onCreate();
    }
}
```

### **2. Head over to Manifest.xml and add the following line to your tag**

```
<application
    android:name=".MyApplicationClass"
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:roundIcon="@mipmap/ic_launcher_round"
    android:supportsRtl="true"
    android:theme="@style/AppTheme">
    ...
</application>
```

### **3. Add the following code above onCreate in MyApplicationClass.java**

```
// This flag should be set to true to enable VectorDrawable support for API < 21
static
{
    AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
}
```

## **Complete code for MyApplicationClass.java**

```
import android.app.Application;
import android.support.v7.app.AppCompatDelegate;

/**
* Created by Renish Patel on 23-May-18.
*/

public class MyApplicationClass extends Application
{
    // This flag should be set to true to enable VectorDrawable support for API < 21
    static
    {
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
    }

    @Override
    public void onCreate()
    {
        super.onCreate();
    }
}
```

**Comment by gsantner** [comment]
then send a PR if it fixes.
